name: Create and Upload Daily YouTube Short

on:
  schedule:
    # Her gün UTC ile 06:00'da çalıştır (Türkiye saati ile sabah 09:00)
    - cron: "0 6 * * *"
  workflow_dispatch: # Manuel olarak tetikleme imkanı

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # FFmpeg'in kurulu olduğundan emin olalım
          sudo apt-get update && sudo apt-get install -y ffmpeg

      # --- YENİ EKLENEN DOĞRULAMA ADIMI ---
      # Bu adım, çalışan main.py dosyasının içeriğini loglara basar.
      - name: Verify main.py content before running
        run: |
          echo "--- Kontrol Ediliyor: main.py dosyasının içeriği ---"
          cat main.py
          echo "----------------------------------------------------"
      # ----------------------------------------
      - name: Run the main script
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          YOUTUBE_CLIENT_SECRETS: ${{ secrets.YOUTUBE_CLIENT_SECRETS }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: python main.py
